services:
  mcp-backend:
    build: .
    container_name: mcp-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: sabrina-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: