version: '3.8'

services:
  mcp-analytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-analytics-api
    ports:
      - "8000:8000"
    environment:
      # MongoDB Configuration
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - DB_NAME=${DB_NAME:-your_database}
      
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Application Settings
      - ENV=${ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    
    volumes:
      # Mount logs directory
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    # depends_on:
    #   - mongodb
    
    networks:
      - mcp-network
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Optional: MongoDB container (if not using external MongoDB)
  # mongodb:
  #   image: mongo:7
  #   container_name: mcp-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-changeme}
  #   volumes:
  #     - mongodb_data:/data/db
  #     - mongodb_config:/data/configdb
  #   restart: unless-stopped
  #   networks:
  #     - mcp-network
    
  #   # Resource limits
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 2G

networks:
  mcp-network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config: